x-ur5e-common: &ur5e-common
  image: nack03/ros2_moveit2_ur5e_grasp:humble

  network_mode: host
  ipc: host
  privileged: true

  environment:
    DISPLAY: ${DISPLAY:-:0}
    WAYLAND_DISPLAY: ${WAYLAND_DISPLAY:-wayland-0}
    XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR:-/mnt/wslg/runtime-dir}
    PULSE_SERVER: ${PULSE_SERVER:-unix:/mnt/wslg/PulseServer}
    QT_X11_NO_MITSHM: "1"

    ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}

    NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
    NVIDIA_DRIVER_CAPABILITIES: ${NVIDIA_DRIVER_CAPABILITIES:-all}

  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /mnt/wslg:/mnt/wslg
    - /dev:/dev
    - ros2_build:/ros2_ws/build
    - ros2_install:/ros2_ws/install
    - ros2_log:/ros2_ws/log

  working_dir: /ros2_ws

  stdin_open: true
  tty: true

services:
  ur5e-grasp:
    <<: *ur5e-common
    container_name: ur5e-grasp
    command: sleep infinity

  simulation:
    <<: *ur5e-common
    container_name: ur5e-grasp-sim
    command:
      - bash
      - -lc
      - |
        set -e
        source /opt/ros/humble/setup.bash
        cd /ros2_ws

        if [ ! -f /ros2_ws/install/setup.bash ]; then
          echo "===== first run: build workspace ====="
          colcon build --event-handlers console_direct+ 
        else
          echo "===== install already exists, skip build ====="
        fi

        source /ros2_ws/install/setup.bash
        ros2 launch ur_bringup simulation.launch.py

  grasp-demo:
    <<: *ur5e-common
    container_name: ur5e-grasp-demo
    command:
      - bash
      - -lc
      - |
        set -e
        source /opt/ros/humble/setup.bash
        cd /ros2_ws

        if [ ! -f /ros2_ws/install/setup.bash ]; then
          echo "===== first run: build workspace ====="
          colcon build --event-handlers console_direct+ \
        else
          echo "===== install already exists, skip build ====="
        fi

        source /ros2_ws/install/setup.bash
        ros2 launch ur_bringup start_grasp.launch.py

volumes:
  ros2_build:
  ros2_install:
  ros2_log:
